### ISSUE TITLE
Links dead ?

### ISSUE THREAD

**Issue by ghost** [goldsborough/Writer#3]
Hello,

It seems links are dead !

Part 1: http://www.binpress.com/tutorial/building-a-text-editor-with-pyqt-part-one/143
Part 2: http://www.binpress.com/tutorial/developing-a-pyqt-text-editor-part-2/145
Part 3: http://www.binpress.com/tutorial/building-a-text-editor-with-pyqt-part-3/147
Part 4: http://www.binpress.com/tutorial/building-a-text-editor-with-pyqt-part-4/148

Is it possible to get tutorials somewhere else ?

Thanks !

**Comment by goldsborough** [comment]
I think BinPress went out of business. I will see if I can get those articles back

**Comment by goldsborough** [comment]
I dug out the links from `web.archive.org`. The README is updated. Thanks for reporting!
